function init(self)
	msg.post("#", "disable")
end




function on_message(self, message_id, message, sender)
	if message_id == hash("show") then
		--msg.post("#", "acquire_input_focus")
		gui.set_render_order(2)
		--menu_proxy = true
		msg.post("#", "enable")
	end
end




function on_input(self, action_id, action)
	if action_id == hash("pause") and action.pressed then pause("main:/main#title_menu_proxy") end

	if pause_id == nil then

	end
end
