function on_message(self, message_id, message, sender)
	if message_id == hash("menu_end") then
		play_intro = false
		allow_title_emojis = false      -- disable emojis
		allow_title_clicks = false      -- disable right click objects

		msg.post("/main#title_screen", "hide_gui")
		go.animate("/main#title_music", "gain", go.PLAYBACK_ONCE_FORWARD, 0, go.EASING_LINEAR, 2.25)

		-- send message to main loader to start game_proxy
		msg.post("main:/main#ctrl", "start_game")
	end
end
