function init(self)
	if score > 0 and level_play == true then
		score = score - 1
	end
	timer.delay(0.04, false, function ()
		msg.post("game_layer2:/main#game_gui", "display_update")
		go.delete()
	end)
end




function update(self, dt)
	if weapon_collide == true then
		msg.post("#pistol", "enable")
		msg.post("#collide_clock", "enable")
	else
		msg.post("#pistol", "disable")
		msg.post("#collide_clock", "disable")
	end
end
